### ISSUE TITLE
TypeError: document.registerElement is not a function

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/gEDA.js#2]
gEDA.js doesn't work with Firefox 32.0.1 in Windows Vista.
Console error: TypeError: document.registerElement is not a function
